"""baseline schema

Revision ID: 53a16420a6ea
Revises:
Create Date: 2026-06-07 09:47:27.012042

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "53a16420a6ea"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=20), server_default="viewer", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "brand_guidelines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_file_path", sa.String(length=500), nullable=True),
        sa.Column("primary_colors", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("secondary_colors", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("primary_font", sa.String(length=100), server_default="Arial", nullable=True),
        sa.Column("secondary_font", sa.String(length=100), nullable=True),
        sa.Column("brand_voice", sa.Text(), nullable=True),
        sa.Column("photography_style", sa.Text(), nullable=True),
        sa.Column("prohibited_elements", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("logo_config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("text_customization", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("post_processing", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_extracted_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "campaigns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.String(length=100), nullable=False),
        sa.Column("campaign_name", sa.String(length=255), nullable=False),
        sa.Column("brand_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("brief", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("image_backend", sa.String(length=50), server_default="firefly", nullable=False),
        sa.Column(
            "target_locales", postgresql.JSONB(astext_type=sa.Text()), server_default='["en-US"]', nullable=False
        ),
        sa.Column(
            "aspect_ratios",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='["1:1","9:16","16:9"]',
            nullable=False,
        ),
        sa.Column("brand_guidelines_id", sa.UUID(), nullable=True),
        sa.Column("localization_guidelines", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("legal_guidelines", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_guidelines_id"],
            ["brand_guidelines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id"),
    )
    op.create_index("ix_campaigns_brand_name", "campaigns", ["brand_name"], unique=False)
    op.create_index("ix_campaigns_created_by", "campaigns", ["created_by"], unique=False)
    op.create_index("ix_campaigns_status", "campaigns", ["status"], unique=False)
    op.create_table(
        "campaign_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("technical_metrics", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("business_metrics", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("recorded_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_campaign_metrics_campaign_id", "campaign_metrics", ["campaign_id"], unique=False)
    op.create_index("ix_campaign_metrics_recorded_at", "campaign_metrics", ["recorded_at"], unique=False)
    op.create_table(
        "campaign_products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.String(length=100), nullable=False),
        sa.Column("product_name", sa.String(length=255), nullable=False),
        sa.Column("product_description", sa.Text(), nullable=False),
        sa.Column("product_category", sa.String(length=100), nullable=False),
        sa.Column("key_features", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("generation_prompt", sa.Text(), nullable=True),
        sa.Column("hero_image_path", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "product_id", name="uq_campaign_product"),
    )
    op.create_index("ix_campaign_products_campaign_id", "campaign_products", ["campaign_id"], unique=False)
    op.create_index("ix_campaign_products_product_category", "campaign_products", ["product_category"], unique=False)
    op.create_table(
        "compliance_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("is_compliant", sa.Boolean(), nullable=False),
        sa.Column("violations", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("checked_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_compliance_reports_campaign_id", "compliance_reports", ["campaign_id"], unique=False)
    op.create_index("ix_compliance_reports_is_compliant", "compliance_reports", ["is_compliant"], unique=False)
    op.create_table(
        "generated_assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.String(length=100), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("aspect_ratio", sa.String(length=10), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("generation_method", sa.String(length=50), nullable=False),
        sa.Column("generation_time_ms", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "product_id", "locale", "aspect_ratio", name="uq_asset_variant"),
    )
    op.create_index("ix_generated_assets_campaign_id", "generated_assets", ["campaign_id"], unique=False)
    op.create_index("ix_generated_assets_generation_method", "generated_assets", ["generation_method"], unique=False)
    op.create_index("ix_generated_assets_locale", "generated_assets", ["locale"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="queued", nullable=False),
        sa.Column("progress_percent", sa.Integer(), server_default="0", nullable=False),
        sa.Column("current_stage", sa.String(length=50), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_trace", sa.Text(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_jobs_campaign_id", "jobs", ["campaign_id"], unique=False)
    op.create_index("ix_jobs_status", "jobs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_jobs_status", table_name="jobs")
    op.drop_index("ix_jobs_campaign_id", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_generated_assets_locale", table_name="generated_assets")
    op.drop_index("ix_generated_assets_generation_method", table_name="generated_assets")
    op.drop_index("ix_generated_assets_campaign_id", table_name="generated_assets")
    op.drop_table("generated_assets")
    op.drop_index("ix_compliance_reports_is_compliant", table_name="compliance_reports")
    op.drop_index("ix_compliance_reports_campaign_id", table_name="compliance_reports")
    op.drop_table("compliance_reports")
    op.drop_index("ix_campaign_products_product_category", table_name="campaign_products")
    op.drop_index("ix_campaign_products_campaign_id", table_name="campaign_products")
    op.drop_table("campaign_products")
    op.drop_index("ix_campaign_metrics_recorded_at", table_name="campaign_metrics")
    op.drop_index("ix_campaign_metrics_campaign_id", table_name="campaign_metrics")
    op.drop_table("campaign_metrics")
    op.drop_index("ix_campaigns_status", table_name="campaigns")
    op.drop_index("ix_campaigns_created_by", table_name="campaigns")
    op.drop_index("ix_campaigns_brand_name", table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_table("brand_guidelines")
    op.drop_table("users")
    # ### end Alembic commands ###
